create table if not exists public.places (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.places
  add column if not exists image_alt text;

create unique index if not exists places_name_idx
  on public.places (name);

create table if not exists public.holiday_packages (
  id bigint generated by default as identity primary key,
  name text not null,
  duration text not null,
  audience text not null check (audience in ('family', 'couple')),
  description text not null,
  includes text[] not null default '{}',
  price text not null,
  is_featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.stay_packages (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  travel_date date,
  guests text not null,
  selected_package text,
  created_at timestamptz not null default now()
);

alter table public.places enable row level security;
alter table public.holiday_packages enable row level security;
alter table public.stay_packages enable row level security;
alter table public.enquiries enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'places'
      and policyname = 'Public can read places'
  ) then
    create policy "Public can read places"
      on public.places for select
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'holiday_packages'
      and policyname = 'Public can read holiday packages'
  ) then
    create policy "Public can read holiday packages"
      on public.holiday_packages for select
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'stay_packages'
      and policyname = 'Public can read stay packages'
  ) then
    create policy "Public can read stay packages"
      on public.stay_packages for select
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'enquiries'
      and policyname = 'Public can submit enquiries'
  ) then
    create policy "Public can submit enquiries"
      on public.enquiries for insert
      with check (true);
  end if;
end
$$;
